export const CREATE_NODE = ('CREATE_NODE');
export const CREATE_NODE_ERROR = ('CREATE_NODE_ERROR');

export const ADD_CHILD_NODE = ('ADD_CHILD_NODE');
export const ADD_CHILD_NODE_ERROR = ('ADD_CHILD_NODE_ERROR');

export const RENAME_NODE = ('RENAME_NODE');
export const RENAME_NODE_ERROR = ('RENAME_NODE_ERROR');

export const REMOVE_NODE = ('REMOVE_NODE');
export const REMOVE_NODE_ERROR = ('REMOVE_NODE_ERROR');


export const GET_NODE_DATA = ('GET_TREE_DATA');
export const GET_NODE_DATA_ERROR = ('GET_TREE_DATA_ERROR');
export const GET_NODE_DATA_RECEIVED = ('GET_TREE_DATA_RECEIVED');


